prediction_files:
- logs_ec_tune/train_mlp_ec_new_NC_0.5_weight_deeper_MLPLayernorm_2024_06_29__22_49_15_seed_0/predictions_lookup_S50.csv
- logs_ec_tune/train_mlp_ec_new_NC_0.5_weight_deeper_MLPLayernorm_2024_06_30__07_37_54_seed_1/predictions_lookup_S50.csv
- logs_ec_tune/train_mlp_ec_new_NC_0.5_weight_deeper_MLPLayernorm_2024_06_29__22_49_15_seed_2/predictions_lookup_S50.csv
- logs_ec_tune/train_mlp_ec_new_NC_0.5_weight_deeper_MLPLayernorm_2024_07_30__10_29_27_seed_3/predictions_lookup_S50.csv
- logs_ec_tune/train_mlp_ec_new_NC_0.5_weight_deeper_MLPLayernorm_2024_07_30__10_29_46_seed_4/predictions_lookup_S50.csv