prediction_files:
- logs_GO_tune/train_mlp_GO_BP_new_NC_MLPLayernorm_2024_07_17__11_39_52_seed_0/predictions_lookup_scores_flatten_backprop.csv
- logs_GO_tune/train_mlp_GO_BP_new_NC_MLPLayernorm_2024_07_17__11_39_52_seed_1/predictions_lookup_scores_flatten_backprop.csv
- logs_GO_tune/train_mlp_GO_BP_new_NC_MLPLayernorm_2024_07_17__11_39_52_seed_2/predictions_lookup_scores_flatten_backprop.csv
- logs_GO_tune/train_mlp_GO_BP_new_NC_MLPLayernorm_2024_07_25__12_13_30_seed_3/predictions_lookup_scores_flatten_backprop.csv
- logs_GO_tune/train_mlp_GO_BP_new_NC_MLPLayernorm_2024_07_25__12_13_30_seed_4/predictions_lookup_scores_flatten_backprop.csv